tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/piano_tones/piano_tones_mag_noaug.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal
  target_signal_length: 131584
  model:
    class: signalai.models.Spec2Map
    kwargs:
      convs_2d: [8,8,8]
      convs_1d: [512, 256, 128]
      activation: mish
      out_activation: sigmoid
      in_channels: 1
      vertical_channels: 513
      outputs: 85

  transform:
    predict:
      - class: signalai.transformers.STFT
        kwargs:
          phase_as_meta: true
          n_fft: 1024


batch_size: 16
batches: 40000
echo_step: 500
save_step: 1000
average_losses_to_print: 300


criterion:
  name: BCELoss
optimizer:
  name: Adam
  kwargs:
    lr: 0.0002

evaluators:
- class: signalai.evaluators.ItemsEcho
- class: signalai.evaluators.Binary
- class: signalai.evaluators.EBinary

eval_batch_size: 3
eval_batches: 1500
eval_post_transform: false
