tasks: signalai.tasks.data_preparation.*

datasets:
  - class: signalai.datasets.AllToneLoader
    kwargs:
      class_structure:
        piano:
          filename: '/mnt/AXAGO/Datasets/Tone/piano.mp3'
          classes_file: "{CONFIGS_DIR}/data_preparation/tone_identification/piano_tones.csv"

      target_dtype: float16
      meta:
        fs: 48000


split: [1.,0.0,0.0]
load_to_ram: true


processors:
  train:
    to_ram: true
    target_length: 262144
    tracks:
      t0:
        superclasses:
        - piano
        strategy:
          inner_strategy: start
          tones_count_range: [2, 20]
          start_arange: [0, 262144, 8192]
          tone_length_arange: [4096, 32768, 4096]
        transforms:
          base: []
          X: []
          Y: []

    transforms:
      base: []
      X: []
      Y: []

    X: t0.sum_channels()
    Y: t0.stack_signals(only_valid=False).signal_map
