tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/example/augment_magpha.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal

  model:
    class: signalai.models.TimEXception
    kwargs:
      in_channels: 2
      processing_kernels: 128
      output_channels: 8
      activation: SELU
      inner_out_channels: 8
      attention: true
      residual:
        - true
        - false
        - true
        - false
        - true

  transform:
    predict:
      - class: signalai.transformers.STFT
        kwargs:
          phase_as_meta: false

  post_transform:
    predict:
      - class: signalai.transformers.ISTFT
        kwargs:
          phase_as_meta: false


training_params:
  batch_size: 5
  batches: 30
  echo_step: 500
  save_step: 1000
  average_losses_to_print: 300

  criterion:
    name: MSELoss
  optimizer:
    name: Adam
    kwargs:
      lr: 0.01
