tasks: signalai.tasks.data_preparation.*

datasets:
  - class: signalai.datasets.FileLoader
    kwargs:
      class_structure:
        tahovka_normal: tahovka

      base_dir: '/mnt/AXAGO/Datasets/AE stream'
      channels:
        - re_path: 'AE-DATA-conti-7380295766912963-ch2.bin'

      relevant_sample_intervals:
      - [15625000, 62500000]

      loading_params:
        dtype: 'float32'

      target_dtype: float16

      meta:
        fs: 1562500
        category: 0

  - class: signalai.datasets.FileLoader
    kwargs:
      class_structure:
        tahovka_plastized: tahovka

      base_dir: '/mnt/AXAGO/Datasets/AE stream'
      channels:
        - re_path: 'AE-DATA-conti-7380295766912963-ch2.bin'

      relevant_sample_intervals:
      - [966718750, 1010156250]

      loading_params:
        dtype: 'float32'

      target_dtype: float16

      meta:
        fs: 1562500
        category: 1

  - class: signalai.datasets.FileLoader
    kwargs:
      class_structure:
        all_tahovka: all_tahovka

      base_dir: '/mnt/AXAGO/Datasets/AE stream'
      channels:
        - re_path: 'AE-DATA-conti-7380295766912963-ch2.bin'

      loading_params:
        dtype: 'float32'

      target_dtype: float16

      meta:
        fs: 1562500

  - class: signalai.datasets.FileLoader
    kwargs:
      class_structure:
        tahovka_noise: tahovka_noise

      base_dir: '/mnt/AXAGO/Martin/signalai/noise'
      channels:
        - re_path: '.*ch(?P<channel>1).*.bin'
      loading_params:
        dtype: 'float32'

      target_dtype: float16

      meta:
        fs: 1562500


split: [0.95,0.0,0.05]
load_to_ram: true


processors:
  train:
    to_ram: true
    target_length: 32768
    strategy: random
    tracks:
      t0:
        superclasses:
        - tahovka
        equal_classes: true
        transforms:
          base: []
          X: []
          Y: []

    transforms:
      base: []
      X: []
      Y: []

    X: t0
    Y: t0.meta['category']

  all:
    to_ram: false
    target_length: 32768
    stride: 0
    strategy: only_once
    tracks:
      t0:
        superclasses:
        - all_tahovka
        transforms:
          base: []
          X: []
          Y: []

    transforms:
      base: []
      X: []
      Y: []

    X: t0
    Y: None
