tasks: signalai.tasks.data_preparation.*
uses: "{CONFIGS_DIR}/datasets/piano.yaml"
load_to_ram: true

train:
  to_ram: true
  tracks:
    t0:
      class: signalai.strategies.ToneStrategy
      kwargs:
        strategy: start
        tones_count_range: [2, 10]
        start_arange: [0, 262144, 8192]
        tone_length_arange: [4096, 32768, 4096]
        superclasses:
        - all_piano

        transform:
          base:
            - class: signalai.transformers.ChannelJoiner
              kwargs:
                choose_channels:
                  - [[0,1]]

          X:
            - class: signalai.transformers.Lambda
              kwargs:
                lambda: "lambda x: x.sum_channels()"

            - class: signalai.transformers.STFT
              kwargs:
                phase_as_meta: true
                n_fft: 1024
          Y:
            - class: signalai.transformers.TimeMapScale
              kwargs:
                target_length: 511

  transform:
    base: []
    X: []
    Y: []

  X: t0.data_arr
  Y: t0.stack_series(only_valid=False).time_map.astype('float32')


valid: {}


test:
  to_ram: true
  tracks:
    t0:
      class: signalai.strategies.ToneStrategy
      kwargs:
        strategy: start
        tones_count_range: [2, 10]
        start_arange: [0, 262144, 8192]
        tone_length_arange: [4096, 32768, 4096]
        superclasses:
        - piano

        transform:
          base:
            - class: signalai.transformers.ChannelJoiner
              kwargs:
                choose_channels:
                  - [[0,1]]

            - class: signalai.transformers.Reverb
              kwargs:
                transform_chance: 0.2
                room_size: [.0, 1.]
                damping: [.0, 1.]
                wet_level: [.0, 1.]
                dry_level: [.0, 1.]
#                freeze_mode: [.0,.2]

          X:
            - class: signalai.transformers.Lambda
              kwargs:
                lambda: "lambda x: x.sum_channels()"

            - class: signalai.transformers.STFT
              kwargs:
                phase_as_meta: true
                n_fft: 1024
          Y:
            - class: signalai.transformers.TimeMapScale
              kwargs:
                target_length: 511

  transform:
    base: []
    X: []
    Y: []

  X: t0.data_arr
  Y: t0.stack_series(only_valid=False).time_map.astype('float32')
