tasks: signalai.tasks.data_preparation.*
uses: "{CONFIGS_DIR}/datasets/piano_tones.yaml"


generators:
  reverb:
    class: signalai.audio_transformers.Reverb
    kwargs:
      transform_chance: 0.2
      room_size: [.0, 1.]
      damping: [.0, 1.]
      wet_level: [.0, 1.]
      dry_level: [.0, 1.]

  chorus:
    class: signalai.audio_transformers.Chorus
    kwargs:
      transform_chance: 0.2
      centre_delay_ms: [ 6.5, 8.5 ]

  gain:
    class: signalai.audio_transformers.Gain
    kwargs:
      transform_chance: 0.2
      gain_db: [-15., 15.]

  x_lambda:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.data_arr
      apply_to_ts: true

  sum_ts:
    class: signalai.time_series_gen.TimeSeriesSum

  sum_channels:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.sum_channels()
      apply_to_ts: true

  time_map_scale:
    class: signalai.time_series_gen.TimeMapScale
    kwargs:
      first_crop: [512, 512]  # needed when using STFT
      target_length: 511

  stft:
    class: signalai.audio_transformers.STFT
    kwargs:
      phase_as_meta: true
      n_fft: 1024

  pruner:
    class: signalai.time_series_gen.ChannelPruner
    kwargs:
      choose_channels: '[{0,1},{2,3},{4,5},{6,7},{8,9},{10,11},{12,13},{14,15},{16,17},{18,19},{20,21},{22,23},{24,25},{26,27},{28,29},{30,31},{32,33},{34,35},{36,37},{38,39},{40,41},{42,43},{44,45},{46,47},{48,49},{50,51},{52,53},{54,55},{56,57},{58,59},{60,61},{62,63},{64,65},{66,67},{68,69},{70,71},{72,73},{74,75},{76,77},{78,79},{80,81},{82,83},{84,85},{86,87},{88,89},{90,91},{92,93},{94,95},{96,97},{98,99},{100,101},{102,103},{104,105},{106,107},{108,109},{110,111},{112,113},{114,115},{116,117},{118,119},{120,121},{122,123},{124,125},{126,127},{128,129},{130,131},{132,133},{134,135},{136,137},{138,139},{140,141},{142,143},{144,145},{146,147},{148,149},{150,151},{152,153},{154,155},{156,157},{158,159},{160,161},{162,163},{164,165},{166,167},{168,169}]'


data_graph_train:
  =Z:
    gain:
      pruner:
        piano_train

  =X:
    x_lambda:
      stft:
        reverb:
          sum_channels: Z

  =Y:
    time_map_scale: Z


train_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_valid:
  =Z:
    pruner: piano_test

  =X:
    x_lambda:
      stft:
        sum_channels: Z

  =Y:
    time_map_scale: Z

valid_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_test:
  =Z:
    pruner: piano_test

  =X:
    x_lambda:
      stft:
        sum_channels: Z

  =Y:
    time_map_scale: Z

test_gen:
  inputs:
    - X
  outputs:
    - Y
