model_info:
  class: signalai.torch_core.InceptionTime
  type: torch  # tf

model_params:
  build_config:
    - bottleneck_channels: 32
      kernel_sizes: [11, 21, 41]
      n_filters: 32
#    - bottleneck_channels: 32
#      kernel_sizes: [11, 21, 41]
#      n_filters: 32
  in_channels: 2
  outputs: -2

training_params:
  batch_size: 16
  batches: 50000
  echo_step: 500
  save_step: 1500
  average_losses_to_print: 300
  output_type: signal

  output_name: karaoke{batch_id}
  criterion:
    name: MSELoss
  optimizer:
    name: Adam
    kwargs:
      lr: 0.01