tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/freq_splitter/freq_splitter.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  model:
    class: signalai.torch_core.InceptionTime
    kwargs:
      build_config:
        - bottleneck_channels: 32
          kernel_sizes: [11, 21, 41]
          n_filters: 32
      in_channels: 1
      linear: 1


training_params:
  batch_size: 16
  batches: 5000
  echo_step: 500
  save_step: 1500
  average_losses_to_print: 300
  evaluator:
    class: signalai.evaluators.torch_evaluators.Tahovka

  output_name: tahovka{batch_id}
  criterion:
    name: BCELoss
  optimizer:
    name: Adam
    kwargs:
      lr: 0.01