tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/random_cyclic_plastic_loading/identity/2d/sequence_kiso1_steps12_depspcr.yaml"


model:
  class: signalai.torch_model.TorchTimeSeriesModel
  kwargs:
    taken_length: null
    model_definition:
      model:
        class: signalai.models.gru.InceptionGRU
        kwargs:
          input_size: 12
          hidden_size: 128
          layers: 4
          outputs: 7
          kernel_sizes: [5, 9, 13]
          bias: true

    device: cuda
    training_params:
      epochs: 30
      dataloader_kwargs:
        batch_size: 64
        shuffle: false
        num_workers: 12
      max_batches: 1000
      save_epoch_step: 1
      # save_batch_step: 1500
      # early_stopping_regression: 1500
      # early_stopping_average_losses: 300
      set:
        0:
          criterion:
            name: MSELoss
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 1.0e-4
        15:
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 1.0e-5
        25:
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 1.0e-6

    training_echo:
      # echo_step: 5000
      metrics: {}
      init_eval: true
      evaluators:
        - class: signalai.evaluators.L2PieceWise
        - class: signalai.evaluators.L2Total
      evaluation_params:
        dataloader_kwargs:
          batch_size: 64
          shuffle: false
          num_workers: 8

        max_batches: 250


generators:
  x_lambda:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: '(w.data_arr - 10.35) / 235.73'
      apply_to_ts: true


transform_graph:
  =pre_transform:
    x_lambda


evaluators:
  - class: signalai.evaluators.L2PieceWise
  - class: signalai.evaluators.L2Total
#- class: signalai.evaluators.AutoEncoderL12
#  kwargs:
#    zero_front: 1000
#    zero_end: 1000
#- class: signalai.evaluators.SpectrogramL12
#  kwargs:
#    zero_front: 1000
#    zero_end: 1000
#- class: signalai.evaluators.MELSpectrogramL12
#  kwargs:
#    zero_front: 1000
#    zero_end: 1000

evaluation_params:
  dataloader_kwargs:
    batch_size: 64
    shuffle: false
    num_workers: 8

  max_batches: 2500
