datasets: {}
fake_datasets:
  simple0:
    class: signalai.signal.fake_dataset.ToneGenerator
    kwargs:
      fs: 44100
      freq: [10, 6000]
      noise_ratio: 5
      noise_range: [10, 6000]
  simple1:
    class: signalai.signal.fake_dataset.ToneGenerator
    kwargs:
      fs: 44100
      freq: [6000, 20000]
      noise_ratio: 5
      noise_range: [6000, 20000]

manager_config:
  type: simple_manager

  transformers:
    standardizer:
      class: signalai.signal.transformers.Standardizer
      kwargs:
        mean: 0
        std: 1

  tracks:
    t0:
      datasets:
      - simple0
    t1:
      datasets:
      - simple1

  X: "t0 + t1" # + np.random.normal(loc=0.0, scale=np.random.uniform(0.,np.std(t0.signal)/2), size=[1,32734]).astype(np.float32)"
  Y: "t0 | t1"

default_tracks_config:
  equal_category: true
  next_after_samples: false
  max_signal_length: 32734
  length: 32734
