datasets:
  karaoke:
    folder: '/home/martin/dataset_karaoke'
    channels:
      - re_path: '.*(?P<channel>1).aac'
      - re_path: '.*(?P<channel>2).aac'
      - re_path: '.*(?P<channel>3).aac'
      - re_path: '.*(?P<channel>4).aac'

    splittable: true
    standardize: false


default_signal_info:
  big_endian: true
  signed: true
  fs: 44100
  op_dtype: float16
  to_ram: false
  split: [0.9,0.,0.1]


manager_config:
  type: simple_manager

  transformers:
    standardizer:
      class: signalai.signal.transformers.Standardizer
      kwargs:
        mean: 0
        std: 1

  tracks:
    t0:
      datasets:
      - karaoke
      equal_category: false
      next_after_samples: false

  # X: "t0.signal" # + (noise.signal * np.random.uniform(0.,0.4))"
  X: "t0.join_channels([[0,2,4,6], [1,3,5,7]])" # + np.random.normal(loc=0.0, scale=np.random.uniform(0.,np.std(t0.signal)/2), size=[1,32734]).astype(np.float32)"
  Y: "t0.join_channels([[0,2,4], [1,3,5]])"

default_tracks_config:
  equal_category: true
  next_after_samples: false
  max_signal_length: 327340
  length: 327340
