tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/musdb18/augment.yaml"


model:
  class: signalai.torch_model.TorchTimeSeriesModel
  kwargs:
    taken_length: 65536
    model_definition:
      model:
        class: signalai.models.InceptionTime
        kwargs:
          build_config:
            - bottleneck_channels: 32
              kernel_sizes: [51, 121, 255]
              n_filters: 32
              use_residual: false
          in_channels: 1
          outputs: -4

    device: cuda
    training_params:
      epochs: 1
      dataloader_kwargs:
        batch_size: 10
        shuffle: true
        num_workers: 12

      save_epoch_step: 1
      early_stopping_regression: 1500
      early_stopping_average_losses: 300
      set:
        0:
          criterion:
            name: L1Loss
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 2.0e-3
        5:
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 2.0e-4
        8:
          optimizer:
            name: Adam
            kwargs:
              weight_decay: 1.0e-5
              lr: 1.0e-5

    training_echo:
      # echo_step: 5000
      metrics: {}
      init_eval: true
      evaluators:
        - class: signalai.evaluators.L12
          kwargs:
            zero_front: 1000
            zero_end: 1000
        - class: signalai.evaluators.SpectrogramL12
          kwargs:
            zero_front: 1000
            zero_end: 1000
        - class: signalai.evaluators.MELSpectrogramL12
          kwargs:
            zero_front: 1000
            zero_end: 1000

      evaluation_params:
        dataloader_kwargs:
          batch_size: 10
          shuffle: true
          num_workers: 8

        max_batches: 250


generators:
  x_lambda:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.data_arr
      apply_to_ts: true


transform_graph:
  =pre_transform:
    x_lambda


evaluators:
- class: signalai.evaluators.L12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.SpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.MELSpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000

evaluation_params:
  dataloader_kwargs:
    batch_size: 10
    shuffle: true
    num_workers: 8

  max_batches: 1000
