tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/musdb18/augment.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal
  target_signal_length: 65536  #32768
  model:
    class: signalai.models.InceptionTime
    kwargs:
      build_config:
        - bottleneck_channels: 32
          kernel_sizes: [21, 41, 81]
          n_filters: 32
          use_residual: false
        - bottleneck_channels: 32
          kernel_sizes: [21, 41, 81]
          n_filters: 32
          use_residual: false
        - bottleneck_channels: 16
          kernel_sizes: [11, 21, 41]
          n_filters: 16
          use_residual: false
      in_channels: 1
      outputs: -4


batch_size: 4
batches: 25000
echo_step: 500
save_step: 1500
average_losses_to_print: 300
early_stopping_regression: 1500

criterion:
  name: L1Loss
optimizer:
  name: Adam
  kwargs:
    lr: 0.0001


evaluators:
- class: signalai.evaluators.L12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.AutoEncoderL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.SpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.MELSpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000

eval_batch_size: 5
eval_batches: 1000
