tasks: signalai.tasks.data_preparation.*
load_to_ram: true


datasets:
  - class: signalai.datasets.FileLoader
    kwargs:
      base_dir: '{BASE_DIR}/data/example/dataset'
      channels:
        - re_path: '.*(?P<channel>1).aac' # (?P<class>ww)
        - re_path: '.*(?P<channel>2).aac'
        - re_path: '.*(?P<channel>3).aac'
        - re_path: '.*(?P<channel>4).aac'

      target_dtype: float16

      class_structure:
        karaoke: karaoke_superclass

      split_by_files: true
      fs: 44100
      transform: []


split: [1.,0.,0.]


processors:
  train:
    to_ram: true

    tracks:
      t0:
        superclasses:
        - karaoke_superclass
        equal_classes: false
        strategy: random
        transform:
          base: []
          X:
            - class: signalai.transformers.ChannelJoiner
              kwargs:
                channels: [[0,2,4,6], [1,3,5,7]]
          Y: []

    transform:
      base: []
      X: []
      Y: []

    X: t0
    Y: t0
