tasks: signalai.tasks.processing.*

signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal
  target_signal_length: 263168  #32768
  model:
    class: signalai.models.CascadedASPPNet
    kwargs:
      n_fft: 2048

  transform:
    predict:
      - class: signalai.transformers.STFT
        kwargs:
          phase_as_meta: false
          n_fft: 2048
          hop_length: 1024

  post_transform:
    predict:
      - class: signalai.transformers.ISTFT
        kwargs:
          phase_as_meta: false
          hop_length: 1024


batch_size: 3
batches: 25000
echo_step: 500
save_step: 1000
average_losses_to_print: 300

loss_lambda: "lambda _x, _y, crit: crit(_x[0], _y) * 0.8 + crit(_x[1], _y) * 0.1 + crit(_x[2], _y) * 0.1"
criterion:
  name: L1Loss
optimizer:
  name: Adam
  kwargs:
    lr: 0.0001


evaluators:
- class: signalai.evaluators.L12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.AutoEncoderL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.SpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.MELSpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000

eval_batch_size: 5
eval_batches: 1000
