tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/musdb18/augment_autoencoder.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal
  target_signal_length: 131072
  model:
    class: signalai.models.Simple1DAutoEncoder
    kwargs:
      encoder_convs:
        - in_channels: 1
          out_channels: 2
          kernel_size: 256
          stride: 4

      decoder_convs:
        - in_channels: 2
          out_channels: 1
          kernel_size: 256
          stride: 4


batch_size: 32
batches: 60000
echo_step: 500
save_step: 1000
average_losses_to_print: 300
# early_stopping_regression: 2000

criterion:
  name: L1Loss
optimizer:
  name: Adam
  kwargs:
    lr: 0.0001


evaluators:
- class: signalai.evaluators.L12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.SpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.MELSpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000

eval_batch_size: 5
eval_batches: 1000
