tasks: signalai.tasks.data_preparation.*
load_to_ram: true


datasets:
  - class: signalai.datasets.FileLoader
    kwargs:
      base_dir: '/home/martin/dataset_karaoke'
      channels:
        - re_path: '.*(?P<channel>1).aac' # (?P<class>ww)
        - re_path: '.*(?P<channel>2).aac'
        - re_path: '.*(?P<channel>3).aac'
        - re_path: '.*(?P<channel>4).aac'

      target_dtype: float16

      class_structure:
        karaoke: karaoke_superclass

      split_by_files: true
      fs: 44100
      transform: []


split: [1.,0.,0.]


processors:
  train:
    to_ram: true
    target_length: 65536  #32768
    tracks:
      t0:
        superclasses:
        - karaoke_superclass
        equal_classes: false
        strategy: random
        transform:
          base:
            - class: signalai.transformers.ChannelJoiner
              kwargs:
                choose_channels:
                  - [[0],[2],[4],[6]]
                  - [[1],[2],[4],[6]]
                  - [[0],[3],[4],[6]]
                  - [[1],[3],[4],[6]]
                  - [[0],[2],[5],[6]]
                  - [[1],[2],[5],[6]]
                  - [[0],[3],[5],[6]]
                  - [[1],[3],[5],[6]]
                  - [[0],[2],[4],[7]]
                  - [[1],[2],[4],[7]]
                  - [[0],[3],[4],[7]]
                  - [[1],[3],[4],[7]]
                  - [[0],[2],[5],[7]]
                  - [[1],[2],[5],[7]]
                  - [[0],[3],[5],[7]]
                  - [[1],[3],[5],[7]]

            - class: signalai.transformers.Reverb
              kwargs:
                transform_chance: 0.2
                room_size: [.0, 1.]
                damping: [.0, 1.]
                wet_level: [.0, 1.]
                dry_level: [.0, 1.]
                freeze_mode: [.0,.2]

            - class: signalai.transformers.Gain
              kwargs:
                transform_chance: 0.2
                gain_db: [-15., 15.]

#            - class: signalai.transformers.Phaser
#              kwargs:
#                transform_chance: 0.2

            - class: signalai.transformers.Chorus
              kwargs:
                transform_chance: 0.2
                centre_delay_ms: [6.5, 8.5]
          X:
            - class: signalai.transformers.ChannelJoiner
            - class: signalai.transformers.STFT
              kwargs:
                phase_as_meta: true
          Y:
            - class: signalai.transformers.STFT
              kwargs:
                phase_as_meta: true

    transform:
      base: []
      X: []
      Y: []

    X: t0
    Y: t0
