tasks: signalai.tasks.data_preparation.*

datasets:
  - class: signalai.datasets.ToneGenerator
    kwargs:
      class_structure:
        low_freq: low_freq

      fs: 44100
      freq: [10, 6000]
      noise_ratio: 5
      noise_range: [10, 6000]
      transform: []

  - class: signalai.datasets.ToneGenerator
    kwargs:
      class_structure:
        high_freq: high_freq

      fs: 44100
      freq: [6000, 20000]
      noise_ratio: 5
      noise_range: [6000, 20000]
      transform: []


split: [1.,0.,0.]


processors:
  train:
    to_ram: true
    strategy: random
    target_length: 32768
    tracks:
      t0:
        superclasses:
        - low_freq
        equal_classes: true
        transform:
          base: []
          X: []
          Y: []

      t1:
        superclasses:
        - high_freq
        equal_classes: true
        transform:
          base: []
          X: []
          Y: []

    transform:
      base: []
      X: []
      Y: []

    X: t0 + t1
    Y: t0 | t1
