tasks: signalai.tasks.processing.*
uses: "{CONFIGS_DIR}/data_preparation/musdb18/augment.yaml"


signal_model_config:
  signal_model_type: torch_signal_model
  output_type: signal
  target_signal_length: 65536  #32768
  model:
    class: signalai.models.SEModel
    kwargs:
      n_filters: 256
      processing_kernels: 32
      kernel_sizes: [128, 256]
      output_channels: 4
      inner_out_channels: 4
      attention: true
      output_separately: false
      use_exception: false


batch_size: 12
batches: 20000
echo_step: 500
save_step: 1000
average_losses_to_print: 300
early_stopping_regression: 5000

criterion:
  name: L1Loss
optimizer:
  name: Adam
  kwargs:
    lr: 0.001


evaluators:
- class: signalai.evaluators.L12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.AutoEncoderL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.SpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000
- class: signalai.evaluators.MELSpectrogramL12
  kwargs:
    zero_front: 1000
    zero_end: 1000

eval_batch_size: 5
eval_batches: 1000
