tasks: signalai.tasks.datasets.*

datasets:
  - class: signalai.datasets.FileLoader
    kwargs:
      base_dir: '/home/martin/BigData/dataset_karaoke/train'
      channels:
        - re_path: '.*(?P<channel>1).aac' # (?P<class>ww)
        - re_path: '.*(?P<channel>2).aac'
        - re_path: '.*(?P<channel>3).aac'
        - re_path: '.*(?P<channel>4).aac'

      target_dtype: float16
      purpose: train

      class_structure:
        karaoke: karaoke_superclass

      split_by_files: true
      fs: 44100
      transform: []

  - class: signalai.datasets.FileLoader
    kwargs:
      base_dir: '/home/martin/BigData/dataset_karaoke/test'
      channels:
        - re_path: '.*(?P<channel>1).aac' # (?P<class>ww)
        - re_path: '.*(?P<channel>2).aac'
        - re_path: '.*(?P<channel>3).aac'
        - re_path: '.*(?P<channel>4).aac'

      target_dtype: float16
      purpose: test

      class_structure:
        karaoke_test: karaoke_test_superclass

      split_by_files: true
      fs: 44100
      transform: []
