tasks: signalai.tasks.datasets.*

datasets:
  piano_train:
    class: signalai.datasets.events_gen.CSVEventsGen
    kwargs:
      file_path: '{DATA_DIR}/tones/piano.mp3'
      csv_file: "{CONFIGS_DIR}/datasets/piano_tones.csv"

      target_dtype: float16
      meta:
        fs: 48000

      tones_count_range: [2, 10]
      start_arange: [0, 262144, 8192]
      tone_length_arange: [8192, 65536, 4096]

  piano_test:
    class: signalai.datasets.events_gen.CSVEventsGen
    kwargs:
      file_path: '{DATA_DIR}/tones/*klavir-r*.mp3'
      csv_file: "{CONFIGS_DIR}/datasets/piano_tones.csv"

      target_dtype: float16
      meta:
        fs: 48000

      tones_count_range: [2, 10]
      start_arange: [0, 262144, 8192]
      tone_length_arange: [4096, 32768, 4096]
