tasks: signalai.tasks.data_preparation.*
uses: "{CONFIGS_DIR}/datasets/tensile_test.yaml"


generators:
  x_lambda:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.data_arr
      apply_to_ts: true

  y_lambda:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: np.array([w.meta['category']])
      apply_to_ts: true


data_graph_train:
  =Z:
    experiment_train
  =X:
    x_lambda: Z
  =Y:
    y_lambda: Z

train_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_valid:
  =Z:
    experiment_test
  =X:
    x_lambda: Z
  =Y:
    y_lambda: Z

valid_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_test:
  =Z:
    experiment_test
  =X:
    x_lambda: Z
  =Y:
    y_lambda: Z

test_gen:
  inputs:
    - X
  outputs:
    - Y
