tasks: signalai.tasks.data_preparation.*
uses: "{CONFIGS_DIR}/datasets/musdb18.yaml"
load_to_ram: true


generators:
  reverb:
    class: signalai.audio_transformers.Reverb
    kwargs:
      transform_chance: 0.2
      room_size: [.0, 1.]
      damping: [.0, 1.]
      wet_level: [.0, 1.]
      dry_level: [.0, 1.]

  gain:
    class: signalai.audio_transformers.Gain
    kwargs:
      transform_chance: 0.2
      gain_db: [-5., 5.]

  data_arr:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.data_arr
      apply_to_ts: true

  pruner:
    class: signalai.time_series_gen.ChannelPruner
    kwargs:
      choose_channels: '[{0,1}, {2,3}, {4,5}, {6,7}]'

  instrument_pruner:
    class: signalai.time_series_gen.ChannelPruner
    kwargs:
      choose_channels: '[1]'

  sum_channels:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.sum_channels()
      apply_to_ts: true

  stft:
    class: signalai.audio_transformers.STFT
    kwargs:
      phase_as_meta: false
      n_fft: 2048
      hop_length: 1024


data_graph_train:
  =Z:
    reverb:
      gain:
        pruner:
          karaoke_train

  =X:
    data_arr:
      stft:
        sum_channels: Z

  =Y:
    data_arr:
      stft:
        instrument_pruner: Z

train_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_valid:
  =Z:
    reverb:
      gain:
        pruner:
          karaoke_test

  =X:
    data_arr:
      stft:
        sum_channels: Z

  =Y:
    data_arr:
      stft:
        instrument_pruner: Z

valid_gen:
  inputs:
    - X
  outputs:
    - Y


data_graph_test:
  =Z:
    reverb:
      gain:
        pruner:
          karaoke_test

  =X:
    data_arr:
      stft:
        sum_channels: Z

  =Y:
    data_arr:
      stft:
        instrument_pruner: Z

test_gen:
  inputs:
    - X
  outputs:
    - Y
