tasks: signalai.tasks.data_preparation.*
uses: "{CONFIGS_DIR}/datasets/musdb18.yaml"
load_to_ram: true


generators:
  reverb:
    class: signalai.audio_transformers.Reverb
    kwargs:
      transform_chance: 0.2
      room_size: [.0, 1.]
      damping: [.0, 1.]
      wet_level: [.0, 1.]
      dry_level: [.0, 1.]

  gain:
    class: signalai.audio_transformers.Gain
    kwargs:
      transform_chance: 0.2
      gain_db: [-15., 15.]

  chorus:
    class: signalai.audio_transformers.Chorus
    kwargs:
      transform_chance: 0.2
      centre_delay_ms: [ 6.5, 8.5 ]

  data_arr:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.data_arr
      apply_to_ts: true

  pruner:
    class: signalai.time_series_gen.ChannelPruner
    kwargs:
      choose_channels: '[{0,1}, {2,3}, {4,5}, {6,7}]'

  instrument_pruner:
    class: signalai.time_series_gen.ChannelPruner
    kwargs:
      choose_channels: '[3]'

  sum_channels:
    class: signalai.time_series_gen.LambdaTransformer
    kwargs:
      lambda_w: w.sum_channels()
      apply_to_ts: true

  stft:
    class: signalai.audio_transformers.STFT
    kwargs:
      phase_as_meta: false
      n_fft: 2048
      hop_length: 1024


data_graph:
  =Z:
    chorus:
      gain:
        reverb:
          pruner:
            karaoke_train

  =X:
    data_arr:
      stft:
        sum_channels: Z

  =Y:
    data_arr:
      stft:
        instrument_pruner: Z

  =Z_test:
    chorus:
      gain:
        reverb:
          pruner:
            karaoke_test

  =X_test:
    data_arr:
      stft:
        sum_channels: Z_test

  =Y_test:
    data_arr:
      stft:
        instrument_pruner: Z_test


train_gen:
  inputs:
    - X
  outputs:
    - Y

valid_gen:
  inputs:
    - X_test
  outputs:
    - Y_test

test_gen:
  inputs:
    - X_test
  outputs:
    - Y_test
